### ISSUE TITLE
What it the TrajectoryCritic in your code

### ISSUE THREAD

**Issue by junleiz** [DigiRL-agent/digirl#2]
Hello, thank you for your excellent work. I am confused about the class TrajectoryCritic. The input size is 768. What is the TrajectoryCritic used for. It seems that it will not receive image features but the comment is "VLM critic using image features"

**Comment by BiEchi** [comment]
Hi, the `TrajectoryCritic` is the instruction-level critic as described in the paper. Moreover, `VLMDoubleCritic` is the step-level critic. Please refer to the figure below as described in our [paper](https://arxiv.org/pdf/2406.11896).

<img width="1128" alt="image" src="https://github.com/DigiRL-agent/digirl/assets/60613238/262aa6a6-e6cd-48c4-a69d-5b1066b17a46">

**Comment by junleiz** [comment]
Thanks!

**Comment by junleiz** [comment]
Sorry to bother. I am another questions.

1. Why the `VLMDoubleCritic` output v1,v2 two values;
2. Where you filter the A > H/1 in your code... I have not find it

**Comment by BiEchi** [comment]
Would like some input from you here @YifeiZhou02

**Comment by YifeiZhou02** [comment]
1, It is a double-q learning trick also used by ILQL (https://arxiv.org/abs/2206.11871) and ArCHer (https://arxiv.org/abs/2402.19446). In many deep rl problems, training two critics and take a min over the two critics can often reduce over-estimation errors of the critic https://arxiv.org/abs/1509.06461.
2, Please check here: https://github.com/DigiRL-agent/digirl/blob/master/digirl/algorithms/digirl/trainer.py#L150. Currently it is hard-coded as 0.05 (1/20), will update it to be the same as 1/H as in the paper. Sorry for the confusion.

**Comment by junleiz** [comment]
Thanks!
