### ISSUE TITLE
Issue of 'Timeout while accessing actions' when reproducing the code

### ISSUE THREAD

**Issue by Wuzheng02** [DigiRL-agent/digirl#23]
Hello, when I was reproducing your code, I successfully configured the environment (screenshot.py runs normally). However, after running python run.py --config-path config/main --config-name digirl_online, I encountered the following error:

**Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:16<00:00,  8.07s/it]
starting appium server at port  6652
starting appium server at port  6653
starting appium server at port  6654
starting appium server at port  6655
starting appium server at port  6656
starting appium server at port  6657
starting appium server at port  6658
starting appium server at port  6659
start iterations
  0%|                                                                                                                                                       | 0/600 [00:00<?, ?it/s]KO: authentication token does not match ~/.emulator_console_auth_token
KO: unknown command, try 'help'
emulator-5554 has been shut down.
Copying the AVD folder from /data/home/wuzh/.android/avd/test_Android.avd to /data/home/wuzh/.android/avd/test1.avd
Copying the AVD folder from /data/home/wuzh/.android/avd/test_Android.avd to /data/home/wuzh/.android/avd/test2.avd
Copying the AVD folder from /data/home/wuzh/.android/avd/test_Android.avd to /data/home/wuzh/.android/avd/test3.avd
Copying the AVD folder from /data/home/wuzh/.android/avd/test_Android.avd to /data/home/wuzh/.android/avd/test4.avd
Copying the AVD folder from /data/home/wuzh/.android/avd/test_Android.avd to /data/home/wuzh/.android/avd/test5.avd
Copying the AVD folder from /data/home/wuzh/.android/avd/test_Android.avd to /data/home/wuzh/.android/avd/test6.avd
Copying the AVD folder from /data/home/wuzh/.android/avd/test_Android.avd to /data/home/wuzh/.android/avd/test7.avd
Copying the AVD folder from /data/home/wuzh/.android/avd/test_Android.avd to /data/home/wuzh/.android/avd/test8.avd
Starting the Emulator
executing command /data/home/wuzh/.android/emulator/emulator -avd test1 "-no-audio" "-skip-adb-auth" "-no-boot-anim" "-gpu" "auto" "-no-snapshot-save" -port 5554 -no-window
Starting the Emulator
executing command /data/home/wuzh/.android/emulator/emulator -avd test2 "-no-audio" "-skip-adb-auth" "-no-boot-anim" "-gpu" "auto" "-no-snapshot-save" -port 5556 -no-window
Starting the Emulator
executing command /data/home/wuzh/.android/emulator/emulator -avd test3 "-no-audio" "-skip-adb-auth" "-no-boot-anim" "-gpu" "auto" "-no-snapshot-save" -port 5558 -no-window
Starting the Emulator
executing command /data/home/wuzh/.android/emulator/emulator -avd test4 "-no-audio" "-skip-adb-auth" "-no-boot-anim" "-gpu" "auto" "-no-snapshot-save" -port 5560 -no-window
Starting the Emulator
executing command /data/home/wuzh/.android/emulator/emulator -avd test5 "-no-audio" "-skip-adb-auth" "-no-boot-anim" "-gpu" "auto" "-no-snapshot-save" -port 5562 -no-window
Starting the Emulator
executing command /data/home/wuzh/.android/emulator/emulator -avd test6 "-no-audio" "-skip-adb-auth" "-no-boot-anim" "-gpu" "auto" "-no-snapshot-save" -port 5564 -no-window
Starting the Emulator
executing command /data/home/wuzh/.android/emulator/emulator -avd test7 "-no-audio" "-skip-adb-auth" "-no-boot-anim" "-gpu" "auto" "-no-snapshot-save" -port 5566 -no-window
Starting the Emulator
executing command /data/home/wuzh/.android/emulator/emulator -avd test8 "-no-audio" "-skip-adb-auth" "-no-boot-anim" "-gpu" "auto" "-no-snapshot-save" -port 5568 -no-window
connected!
connected!
connected!
connected!
connected!
connected!
connected!
connected!
Timeout while accessing actions
Timeout while accessing actions
Timeout while accessing actions
Error in environment interaction
Traceback (most recent call last):
  File "/data/home/wuzh/digirl/digirl/environment/env_utils.py", line 89, in batch_interact_environment
    action = agent.get_action(batch_obs, torch.cat([i.unsqueeze(0) for i in batch_img], dim = 0))
  File "/data/home/wuzh/digirl/digirl/models/autoui_agent.py", line 81, in get_action
    raw_action = self.tokenizer.batch_decode(outputs, skip_special_tokens  = True)
UnboundLocalError: local variable 'outputs' referenced before assignment

local variable 'outputs' referenced before assignment
Resetting appium
KO: authentication token does not match ~/.emulator_console_auth_token
KO: unknown command, try 'help'
emulator-5554 has been shut down.
OK: killing emulator, bye bye
OK
emulator-5556 has been shut down.
OK: killing emulator, bye bye
OK
emulator-5558 has been shut down.
OK: killing emulator, bye bye
OK
emulator-5560 has been shut down.
OK: killing emulator, bye bye
OK
emulator-5562 has been shut down.
OK: killing emulator, bye bye
OK
emulator-5564 has been shut down.
OK: killing emulator, bye bye
OKr, bye bye
OK
emulator-5564 has been shut down.
OK: killing emulator, bye bye
OK
emulator-5566 has been shut down.
OK: killing emulator, bye bye
OK
emulator-5568 has been shut down.
[75ed8d3b][Logcat] Logcat terminated with code 255, signal null
[3864973f][Logcat] Logcat terminated with code 255, signal null
[92a55bd3][Logcat] Logcat terminated with code 255, signal null
[56ca0f3d][Logcat] Logcat terminated with code 255, signal null
[12a4d8ed][Logcat] Logcat terminated with code 255, signal null
[dd594866][Logcat] Logcat terminated with code 255, signal null
[ec775a30][Logcat] Logcat terminated with code 255, signal null**

**Comment by BiEchi** [comment]
If possible, please use English to communicate, this helps broaden the audience.
Did you change the code in `autoui_agent.py`? This problem should not happen with the original codebase.

**Comment by Wuzheng02** [comment]
Thank you for your answer. I finally solved the problem by reconfiguring the environment.

**Comment by sailaoda** [comment]
> Thank you for your answer. I finally solved the problem by reconfiguring the environment.

Hello, I also encountered a situation like Timeout while accessing actions in the process of reproduction. How did you reconfigure the environment specifically, all of them or which components
