### ISSUE TITLE
A few questions regarding code reproduction.

### ISSUE THREAD

**Issue by Wuzheng02** [DigiRL-agent/digirl#25]
Regarding the reproduction of your code, I have a few more questions.

(1) I am now able to run the offline method successfully after resolving the previous issue. However, during the training of the online method, it eventually gets stuck at the following point:

> connected!
> connected!
> connected!
> connected!
> connected!
> connected!
> connected!
> connected!
> Environment stpes 1
> getting actions!
> Task: How much does the LG TV cost?, image: /data/home/wuzh/logs/digirl-general-offline/images/test2/1729776551.5758123_1.png
> Task: Search for hotels in London, image: /data/home/wuzh/logs/digirl-general-offline/images/test1/1729776551.5767486_1.png
> Task: How big is the universe?, image: /data/home/wuzh/logs/digirl-general-offline/images/test4/1729776551.5779502_1.png
> Task: How much does the Vizio TV cost?, image: /data/home/wuzh/logs/digirl-general-offline/images/test5/1729776551.577304_1.png
> skipping evaluation due to previously seen image, current img_matrix size:  5
> skipping evaluation due to previously seen image, current img_matrix size:  5
> skipping evaluation due to previously seen image, current img_matrix size:  5
> skipping evaluation due to previously seen image, current img_matrix size:  5

(2) When loading the checkpoint you provided for eval-only, the following issue occurs: 

> Failed to connect to the appium server: Message: An unknown server-side error occurred while processing the command. Original error: Error getting device API level. Original error: Error executing adbExec. Original error: 'Command '/data/home/wuzh/.android/platform-tools/adb -P 5037 -s emulator-5556 shell getprop ro.build.version.sdk' timed out after 120000ms'. Try to increase the 120000ms adb execution timeout represented by 'adbExecTimeout' capability
> Stacktrace:
> UnknownError: An unknown server-side error occurred while processing the command. Original error: Error getting device API level. Original error: Error executing adbExec. Original error: 'Command '/data/home/wuzh/.android/platform-tools/adb -P 5037 -s emulator-5556 shell getprop ro.build.version.sdk' timed out after 120000ms'. Try to increase the 120000ms adb execution timeout represented by 'adbExecTimeout' capability
>     at getResponseForW3CError (/usr/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)
>     at asyncHandler (/usr/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)
>  Retrying

(3) I noticed that the following prompt appears in both of these error cases. Could this be causally related to the failures?

> KO: authentication token does not match ~/.emulator_console_auth_token
> KO: unknown command, try 'help'
> emulator-5554 has been shut down.
> KO: authentication token does not match ~/.emulator_console_auth_token
> KO: unknown command, try 'help'
> emulator-5556 has been shut down.
> OK: killing emulator, bye bye
> OK
> emulator-5558 has been shut down.
> OK: killing emulator, bye bye
> OK
> emulator-5560 has been shut down.
> OK: killing emulator, bye bye
> OK
> emulator-5562 has been shut down.
> OK: killing emulator, bye bye
> OK
> emulator-5564 has been shut down.
> OK: killing emulator, bye bye

**Comment by BiEchi** [comment]
Thanks for your interest in our work.

(1) Would you like to elaborate on what "stuck" means?
(2) You can safely ignore this error, it will be handled automatically (i.e. after a while the retry gets over this issue).
(3) This means there's something wrong with your installation of the emulator. Please try re-installing the environment.

**Comment by Wuzheng02** [comment]
"Stuck" means that after reaching this line, there will be no further output.

Additionally, I found through code debugging that the code gets stuck at the line 

> response_text = call_gemini(self.client, system_msg, prompt, cot_image_list, image_path)

 in the

>  _evaluate

 function.
 
 
 To be more precise, it's at the line 

> response = client.generate_content 

in the 

> call_gemini

 function.

**Comment by BiEchi** [comment]
Thanks for this debug info. In this case, your Gemini token quota does not allow such high throughput. Try adding `sleep(2)` between Gemini calls.
