### ISSUE TITLE
How can I get the information from the image_path key to rewrite the get_action function?

### ISSUE THREAD

**Issue by Wuzheng02** [DigiRL-agent/digirl#26]
Your paper is very insightful. I have a small question:

When I run in eval_only mode, taking the first example of the general test dataset, I printed the observation parameter of AutoUI's get_action function and it shows

>  ['Previous Actions: Goal: Search for hotels in Washington DC</s>']

I can understand this because AutoUI uses BLIP as the image encoder.

However, when I try to rewrite get_action for a locally deployed multimodal model, such as Qwen2-VL, I find that the parameter passed in is still

>  ['Previous Actions: Goal: Search for hotels in Washington DC</s>']

I need the screenshot information. I noticed that there seems to be an `image_path` key in observation within` cog_agent.py`. How can I get it?

I also noticed that the `image_path` key information appears in the `batch_interact_environment` function in `env_utils.py`. I want to know how I can get its information and put it into my newly written get_action function for Qwen2-VL.

**Comment by Wuzheng02** [comment]
In other words,what I want to do now is to conduct some experiments with a locally deployed multimodal large model in eval_only mode.

**Comment by Wuzheng02** [comment]
I solved the problem because of this: `if env.feature_extractor is not None: batch_obs = [obs["prompt"] for obs in batch_obs]
`
This was the cause, and I don't have any other issues now.

**Comment by BiEchi** [comment]
Thanks for sharing this! Hope it helps others.
