### ISSUE TITLE
[Question] Online-only training result

### ISSUE THREAD

**Issue by junho328** [DigiRL-agent/digirl#27]
It appears that there is an online-only training mode, suggesting that DigiRL online learning was attempted without offline learning. Could you please provide the success rates for AITW general and web shopping when only online learning was conducted?

**Comment by BiEchi** [comment]
Thanks for your interest in our work. We only had some very prelimiary results using online-only mode, it's promising but we did not go for a whole run. You are encouraged to do a run and share here!

**Comment by BiEchi** [comment]
Closed due to inactivity.
