### ISSUE TITLE
Could you open source the code for generating the trajectories?

### ISSUE THREAD

**Issue by GGaoe** [DigiRL-agent/digirl#33]
I have been following your project on DigiRL with great interest.  I would like to kindly request if you would consider open-sourcing the code used for collecting trajectories.  Thank you for considering this request.

**Comment by BiEchi** [comment]
Thanks for your question. This is a duplicate request of #20. Trajectory collection code is already open-sourced.

**Comment by GGaoe** [comment]
> Thanks for your question. This is a duplicate request of #20. Trajectory collection code is already open-sourced.

Thanks for your answer!
