### ISSUE TITLE
Potential Bug in Multi-Machine `scp` Trainer Transfer

### ISSUE THREAD

**Issue by derekywk** [DigiRL-agent/digirl#5]
Thank you for your interesting work in distributing the policies and emulators to work machines to speed up the emulations. While examining the code for multi-machine support, I found a potential bug in `parallel_utils.py`:

https://github.com/DigiRL-agent/digirl/blob/7c4347423ac75ccd3bc95a5469eba761bb98e42c/digirl/algorithms/parallel_utils.py#L47-L49

It appears that the `command` string is constructed outside the `for` loop. Consequently, the `scp` command will always use the last `worker_ip` in the list for all iterations of the new loop. It looks like the trainer is not correctly distributed to all workers.

Could you please take a look at this issue? Thank you for your attention to this matter.

**Comment by BiEchi** [comment]
Thanks for pointing this out! Just fixed the error, please pull for the newest version.

**Comment by BiEchi** [comment]
Closed due to inactivity.
