### ISSUE TITLE
Device image link broken

### ISSUE THREAD

**Issue by zerone91** [DigiRL-agent/digirl#9]
The AVD device image link in the  env_setup/README.md is broken.

**Comment by BiEchi** [comment]
It works on my end - would you please try it again?
https://drive.google.com/drive/folders/1ZGKrWiSoGqg8_NoIGT7rWmiZ8CXToaBF?usp=sharing

**Comment by zerone91** [comment]
Sorry, It seems like a problem of my office network, now it's fine, thank you~

**Comment by BiEchi** [comment]
Closed as the issue is solved.
